import fs from 'node:fs';

// Load word families data
const familiesContent = fs.readFileSync('src/data/wordFamilies.js', 'utf8');
const familyWords = new Set();

// Extract words and roots from the data file
const wordRegex = /word\s*:\s*'([^']+)'/g;
let m;
while ((m = wordRegex.exec(familiesContent)) !== null) {
  familyWords.add(m[1]);
}
const rootRegex = /root\s*:\s*'([^']+)'/g;
while ((m = rootRegex.exec(familiesContent)) !== null) {
  familyWords.add(m[1]);
}

// Load manifest generated by the icon script
const manifest = JSON.parse(fs.readFileSync('scripts/missing-icons-manifest.json', 'utf8'));
const manifestWords = new Set(manifest.map(o => o.word));

// Compare sets
const missing = [...familyWords].filter(w => !manifestWords.has(w));
const extra = [...manifestWords].filter(w => !familyWords.has(w));

console.log('Family words count:', familyWords.size);
console.log('Manifest words count:', manifestWords.size);
console.log('Missing from manifest count:', missing.length);
console.log('Missing words:', missing.join(', '));
console.log('Extra in manifest count:', extra.length);
console.log('Extra words:', extra.join(', '));
