// Chaos plants for the build loop's 2026-09-28/29 fixes. Each plant undoes ONE fix;
// the named unit tests must go RED while it is in place (a plant that stays green is
// a missing test). Runner: scripts/chaos/chaos.mjs (vendored from agent-harness d941f4e).
//   npm run chaos          the gate — every plant, count-pinned (rewrites source; never in pre-commit)
//   npm run chaos:check    anchors only (pre-commit runs this)
// A fix guarded only by an e2e (tap sizes, phone layout, Writing's keep-in-view) has no
// plant here: the gate runs vitest.
const T = (f) => `src/pages/__tests__/${f}.test.js`
const note = 'authored: 2026-09-29 — loop run review'

export const PLANTS = [
  // ── PDF reader ────────────────────────────────────────────────────────────
  {
    name: 'PDF reader: a 2nd Record tap opens a 2nd microphone (d213e12)',
    file: 'src/pages/PDFReader.jsx',
    find: '    if (recBusyRef.current) return\n',
    replace: '',
    tests: [T('pdfReaderRecordStream')],
    note,
  },
  {
    name: 'PDF reader: loading a file mid-recording leaves the mic on (1c5b3f8)',
    file: 'src/pages/PDFReader.jsx',
    find: '    discardRecording()\n    setError(null)\n',
    replace: '    setError(null)\n',
    tests: [T('pdfReaderRecordStream')],
    note,
  },
  {
    // The reader's own isCurrent() progress guard (4fb1d59) is belt-and-braces: translateDocument
    // never reports progress after a cancel, so the plant sits here, where a test can see it.
    name: 'Translate: a cancel during the last retry still reports progress (4fb1d59)',
    file: 'src/lib/translateDocument.js',
    find: '    if (aborted || (!results && signal?.aborted)) break\n',
    replace: '    if (aborted) break\n',
    tests: ['src/lib/__tests__/translateCancel.test.js'],
    note: 'authored: 2026-09-29 — the reader-level plant stayed green; guard + test added at the source',
  },
  {
    name: 'PDF reader: the dense-page offer starts a twin translate run (ca68330)',
    file: 'src/pages/PDFReader.jsx',
    find: '    if (translateAbortRef.current && !translateAbortRef.current.signal.aborted) return\n',
    replace: '',
    tests: [T('pdfReaderTranslateRace')],
    note,
  },
  {
    name: 'PDF reader: Stop → leave still starts Whisper on a dead page (22dac1e)',
    file: 'src/pages/PDFReader.jsx',
    find: '    if (unmountedRef.current) return\n    resetGloss()   // clean slate',
    replace: '    resetGloss()   // clean slate',
    tests: [T('pdfReaderTranscribeUnmount')],
    note,
  },
  {
    name: 'PDF reader: Cancel waits for the OCR/speech engine download (393ba7f)',
    file: 'src/pages/PDFReader.jsx',
    find: "    if (signal.aborted) onAbort()\n    else signal.addEventListener('abort', onAbort, { once: true })\n",
    replace: '',
    tests: [T('pdfReaderEngineLoadCancel')],
    note,
  },
  {
    name: 'OCR engine: Cancel → pick again downloads the engine twice (6db7822)',
    file: 'src/lib/ocrEngine.js',
    find: '  let entry = workerCache.get(langKey)\n',
    replace: '  let entry\n',
    tests: [T('pdfReaderEngineRetryReuse')],
    note,
  },
  {
    name: 'Speech engine: Cancel → pick again downloads Whisper twice (6db7822)',
    file: 'src/lib/transcribeEngine.js',
    find: '  let entry = pipeCache.get(key)\n',
    replace: '  let entry\n',
    tests: [T('pdfReaderEngineRetryReuse')],
    note,
  },
  {
    name: 'PDF open error: pdf.js jargon reaches the learner (18b1eb2, c244088)',
    file: 'src/lib/pdfOpenError.js',
    find: "    ? 'Couldn’t open that file — it may be damaged or not a PDF. Try another file.'\n",
    replace: "    ? (e?.message || 'Failed to read PDF')\n",
    tests: [T('pdfReaderOpenError'), T('importPdfError')],
    note,
  },
  {
    name: 'PDF reader tour: no "Group a phrase" step (2d21ecf)',
    file: 'src/lib/guide/pageGuides.js',
    find: "    { selector: '[data-guide=\"pdf-group\"]', title: 'Group a phrase', body: 'Group on, then drag across words to save one phrase, like jam tangan.', side: 'bottom', align: 'center' },\n",
    replace: '',
    tests: [T('pdfReaderFooterCopy')],
    note,
  },
  // ── Translate ─────────────────────────────────────────────────────────────
  {
    name: 'Translate: Cancel does not stop the gtx word loop (b44088b)',
    file: 'src/lib/translate/providers/gtx.js',
    find: '    if (signal?.aborted) break\n',
    replace: '',
    tests: ['src/lib/__tests__/translateCancel.test.js'],
    note,
  },
  {
    name: 'Translate: a Cancel falls through and spends the next provider (b44088b)',
    file: 'src/lib/translate.js',
    find: '      if (opts.signal?.aborted) break\n',
    replace: '',
    tests: ['src/lib/__tests__/translateCancel.test.js', 'src/lib/__tests__/translate.test.js'],
    note,
  },
  {
    name: 'Translate: a cancelled chunk throws away the words it fetched (b44088b)',
    file: 'src/lib/translateDocument.js',
    find: "      chunk.forEach((w, i) => { if (results[i] && results[i].source !== 'error') out[w] = results[i] })\n",
    replace: '',
    tests: ['src/lib/__tests__/translateCancel.test.js'],
    note,
  },
  // ── Import / Restore ──────────────────────────────────────────────────────
  {
    name: 'Import: an older PDF pick overwrites the newer one (c244088)',
    file: 'src/pages/Import.jsx',
    find: '      if (seq !== pickSeqRef.current) return\n',
    replace: '',
    tests: [T('importPdfError')],
    note,
  },
  {
    name: 'Import: a bad PDF after pasted text implies the text is gone (c244088)',
    file: 'src/pages/Import.jsx',
    find: "{pdfError}{text && ' Your text below is unchanged.'}",
    replace: '{pdfError}',
    tests: [T('importPdfError')],
    note,
  },
  {
    name: 'Import: "Add 1 cards" (3d99799)',
    file: 'src/pages/Import.jsx',
    find: "{readyCount} {readyCount === 1 ? 'card' : 'cards'}",
    replace: '{readyCount} cards',
    tests: [T('importCountLabels')],
    note,
  },
  {
    name: 'Restore: a card export (Export JSON) wipes progress as a "backup" (10ff27b)',
    file: 'src/lib/importBackup.js',
    find: "  if (obj && typeof data.exportDate === 'string' && Array.isArray(data.cards)) return null\n",
    replace: '  if (obj && Array.isArray(data.cards)) return null\n',
    tests: ['src/lib/__tests__/importBackup.test.js'],
    note,
  },
  // ── Store ─────────────────────────────────────────────────────────────────
  {
    name: 'Streak: a freeze day re-awards the 7/14/30 freeze (8fb95bf)',
    file: 'src/store/useStore.js',
    find: 'if (streak.count > state.streak.count && checkStreakMilestone(streak.count)) {',
    replace: 'if (checkStreakMilestone(streak.count)) {',
    tests: ['src/store/__tests__/streakFreezeMilestone.test.js'],
    note,
  },
  {
    name: 'Study plan: "1 cards need attention" (3d99799)',
    file: 'src/store/useStore.js',
    find: "${weakCards.length === 1 ? '1 card needs' : `${weakCards.length} cards need`}",
    replace: '${weakCards.length} cards need',
    tests: ['src/store/__tests__/studyPlanWeakCount.test.js'],
    note,
  },
  // ── Cikgu ─────────────────────────────────────────────────────────────────
  {
    name: 'Cikgu: a signed-out learner is promised AI that refuses them (502c83b)',
    file: 'src/pages/CikguBot.jsx',
    find: '  const aiRefused = !signedIn && !isOpenRouterAvailable()\n',
    replace: '  const aiRefused = false\n',
    tests: [T('cikguSignedOutAiLabel')],
    note,
  },
  {
    name: 'Cikgu: the Expert "not sure" reply sends a signed-out learner to AI (2e5727c)',
    file: 'src/pages/CikguBot.jsx',
    find: "getExpertResponse(content, { aiHint: aiRefused ? 'signin' : 'switch' })",
    replace: 'getExpertResponse(content)',
    tests: [T('cikguHedgeCta')],
    note,
  },
  {
    name: 'Cikgu: AI → Expert can flip mid-answer (3474edf)',
    file: 'src/pages/CikguBot.jsx',
    find: '<button onClick={() => setMode(MODES.EXPERT)} disabled={ai.isLoading || freeAiLoading}',
    replace: '<button onClick={() => setMode(MODES.EXPERT)}',
    tests: [T('cikguModeFlipMidRequest')],
    note,
  },
  {
    name: 'Cikgu: a late reply lands under a newer question (edeabaf)',
    file: 'src/pages/CikguBot.jsx',
    find: "      if (last?.role !== 'user' || last.timestamp !== question.timestamp || last.content !== question.content) return null\n",
    replace: '',
    tests: [T('cikguOrphanQuestion')],
    note,
  },
  {
    name: 'Cikgu: a question orphaned by a reload is never marked unanswered (edeabaf)',
    file: 'src/pages/CikguBot.jsx',
    find: "      useStore.getState().addCikguMessage({ role: 'assistant', content: UNANSWERED })\n",
    replace: '',
    tests: [T('cikguOrphanQuestion')],
    note,
  },
  {
    name: 'Cikgu: OpenRouter waits forever (edeabaf)',
    file: 'src/pages/CikguBot.jsx',
    find: '      const giveUp = setTimeout(() => stop.abort(), OPENROUTER_TIMEOUT_MS)\n',
    replace: '      const giveUp = undefined\n',
    tests: [T('cikguAiTimeout')],
    note,
  },
  {
    name: 'Cikgu: the Send button has no name (1143d0b)',
    file: 'src/pages/CikguBot.jsx',
    find: '          aria-label="Send" title="Send"\n',
    replace: '',
    tests: [T('cikguButtonNames')],
    note,
  },
  // ── Settings ──────────────────────────────────────────────────────────────
  {
    name: 'Settings: a refused action shows the green "done" toast (9ddd055)',
    file: 'src/pages/Settings.jsx',
    find: "background: msgIsError ? 'var(--color-red)' : 'var(--color-green)'",
    replace: "background: 'var(--color-green)'",
    tests: [T('settingsToastTone')],
    note,
  },
  {
    name: 'Settings: toasts are silent to screen readers (be7b23d)',
    file: 'src/pages/Settings.jsx',
    find: '      <FeedbackLive text={msg} />\n',
    replace: '',
    tests: [T('settingsToastTone')],
    note,
  },
  {
    name: 'Settings: a failed "Share My Deck" copy says nothing (be7b23d)',
    file: 'src/pages/Settings.jsx',
    find: ".then(() => flash(shareToastFor(target)), () => flash(\"Couldn't copy the link\", true))",
    replace: '.then(() => flash(shareToastFor(target)))',
    tests: [T('settingsToastTone')],
    note,
  },
  {
    name: 'Settings: "Export CSV (1 cards)" (855eb59)',
    file: 'src/pages/Settings.jsx',
    find: "  const nCards = `${cards.length} card${cards.length === 1 ? '' : 's'}`\n",
    replace: '  const nCards = `${cards.length} cards`\n',
    tests: [T('settingsExportCount')],
    note,
  },
  {
    name: 'Settings: the comparison-link checkbox has no name (ec67f4e)',
    file: 'src/pages/Settings.jsx',
    find: '<label htmlFor="set-comparison-link" className="text-sm">Show comparison link</label>',
    replace: '<span className="text-sm">Show comparison link</span>',
    tests: [T('settingsControlNames')],
    note,
  },
  // ── Dashboard / Roleplay / Tours ──────────────────────────────────────────
  {
    name: 'Dashboard: a first study day reads "1 days" (1f8619e)',
    file: 'src/pages/Dashboard.jsx',
    find: "value: `${streak} ${streak === 1 ? 'day' : 'days'}`",
    replace: 'value: `${streak} days`',
    tests: [T('singularDayCount')],
    note,
  },
  {
    name: 'Dashboard (light): the Smart Session "Start →" chip is 4.07:1 (#51)',
    file: 'src/pages/Dashboard.jsx',
    find: "style={{ background: 'var(--color-card)', color: 'var(--color-blue)' }}",
    replace: "style={{ background: 'color-mix(in srgb, var(--color-blue) 12%, transparent)', color: 'var(--color-blue)' }}",
    tests: [T('dashboardSmartChipContrast')],
    note,
  },
  {
    name: 'Roleplay: out of calls pushes a key that never reaches it (1faca73)',
    file: 'src/pages/Roleplay.jsx',
    find: "Out of AI roleplay for today — it's back tomorrow. Practice mode below still works.",
    replace: 'Out of AI for today. Add your own free key →',
    tests: [T('roleplaySignedOutBanner')],
    note,
  },
  {
    name: 'Tours: a page tour leaves the "New here?" card floating over it (35e0249)',
    file: 'src/hooks/useGuide.js',
    find: "    markGuideSeen('quick')\n",
    replace: '',
    tests: ['src/components/__tests__/guideOfferPageTour.test.js'],
    note,
  },
  // ── Writing ───────────────────────────────────────────────────────────────
  {
    name: 'Writing: changing the task keeps the old task\'s grade (717835a)',
    file: 'src/pages/Writing.jsx',
    find: '    setSelectedTaskId(id)\n    clearGrade()\n',
    replace: '    setSelectedTaskId(id)\n',
    tests: [T('writingTaskChangeClearsGrade')],
    note,
  },
  {
    name: 'Writing: a late AI grade lands after the task changed (717835a)',
    file: 'src/hooks/useWritingEvaluator.js',
    find: '    runRef.current++\n',
    replace: '',
    tests: [T('writingTaskChangeClearsGrade')],
    note,
  },
  {
    name: 'Writing: a keyboard Analyze drops focus while the AI grades (56f885d)',
    file: 'src/pages/Writing.jsx',
    find: 'aria-disabled={isAIGrading || undefined}',
    replace: 'disabled={isAIGrading}',
    tests: [T('writingTaskChangeClearsGrade')],
    note,
  },
  {
    name: 'Writing score: "a.m." / "e.g." end a sentence (0d00636)',
    file: 'src/lib/writingGrader.js',
    find: '  const sents = splitSentenceSpans(text).map(s => s.text)\n',
    replace: '  const sents = text.split(/[.!?]+/).filter(s => s.trim().length > 0)\n',
    tests: ['src/lib/__tests__/writingGrader.test.js'],
    note,
  },
  {
    name: 'Writing score (Malay): "dll." ends a sentence (0d00636)',
    file: 'src/lib/writingGrader.js',
    find: 'splitSentenceSpans(text, NON_FINAL_DOT_MS)',
    replace: 'splitSentenceSpans(text)',
    tests: ['src/lib/__tests__/writingGrader.test.js'],
    note,
  },
  // ── Study ─────────────────────────────────────────────────────────────────
  {
    name: 'Produce mode: a same-meaning word (kamu for awak) is marked wrong (045215f)',
    file: 'src/components/study/ProduceMode.jsx',
    find: '    if (!correct && isSameGlossWord(typed, card, useStore.getState().cards)) return setNearMiss(input.trim())\n',
    replace: '',
    tests: ['src/components/study/__tests__/produceSameGloss.test.js'],
    note,
  },
  {
    name: 'Flashcard produce/reverse: a same-meaning word is marked wrong (045215f)',
    file: 'src/components/study/FlashcardMode.jsx',
    find: '    if (!correct && isSameGlossWord(typed, card, useStore.getState().cards)) return setNearMiss(input.trim())\n',
    replace: '',
    tests: ['src/components/study/__tests__/produceSameGloss.test.js'],
    note,
  },
  // ── CI config ─────────────────────────────────────────────────────────────
  {
    name: 'Dependabot: proposes @huggingface/transformers v4, which deadlocks (de73665)',
    file: '.github/dependabot.yml',
    find: '      - dependency-name: "@huggingface/transformers"\n        update-types: ["version-update:semver-major"]\n',
    replace: '',
    tests: ['src/config/__tests__/dependabotConfig.test.js'],
    note,
  },
]
